mysite/blog/urls.py
from django.urls import path

from .views import post_detail,share_post
from .views import CreatePost,PostListView

from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("",PostListView.as_view(), name="post_list"),
    path("<int:object_id>/detail/",post_detail, name="post_detail"),
    path("new_post/",CreatePost.as_view(), name="new_post"),
    path("<int:object_id>/share/",share_post, name="post_share"),
    path("feed/",LatestPostsFeed(), name="post_feed"),
    


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts":PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls",namespace="blog")),
    path("sitemap.xml",sitemap, {"sitemaps":sitemaps}, name = 'django.contrib.sitemaps.views.sitemaps')

]

mysite/blog/models.py
from django.db import models

from django.contrib.auth.models import User # I am using this
from django.contrib.auth import get_user_model #try this or Use User
from django.utils import timezone
from django.urls import reverse,reverse_lazy

from taggit.managers import TaggableManager # Third party app

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status="published")

class PublishAuthor(models.Manager):
    def get_queryset(self):
        return  super(PublishAuthor,self).get_queryset().filter(status="draft")

class Post(models.Model):
    status_choices = (("draft","Draft"),("published","Published"))

    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=250,unique_for_date='publish')

    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="blog_posts")

    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status = models.CharField(max_length=10,choices=status_choices,default="published")

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Custom manager
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)

    def __str__ (self):
        return self.title

    def get_absolute_url (self):
        return reverse("blog:post_detail",args=[str(self.id)])

class Comment (models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')

    name = models.CharField(max_length=200)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True) # this is used at sitemps.py to get posts which are updated may be i think like this way
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-created"]

    def __str__ (self):
        return "Comment by {} on {}".format(self.name,self.post)

mysite/blog/forms.py
from django import forms

from .models import Comment

class EmailPost(forms.Form):
    name = forms.CharField(max_length=250)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=True,widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name","email","body"]

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404


from .models import Post
from .forms import EmailPost,CommentForm

from django.core.mail import send_mail

from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic.edit import CreateView
from django.views.generic import ListView

# Create your views here.

class PostListView(ListView):
    model = Post
    template_name = "blog/list.html"
    paginate_by = 2

    """ rember must use page_obj for getting pages """



def post_detail (request,object_id):
    post = get_object_or_404(Post,id=object_id)

    # getting all comments
    comments = post.comments.filter(active=True)[:3] # Here the comments from the related_name defined in Comment model in First line

    new_comment = None

    if request.method == "POST":
        # Comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post # Assigning the current post to comment
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render (request,"blog/detail.html",{"post":post,"comments":comments,"new_comment":new_comment,"comment_form":comment_form})


class CreatePost(CreateView):
    model = Post
    template_name = "blog/new_post.html"
    fields = ["title","author","body"]


def share_post(request,object_id):
    post = get_object_or_404(Post,id=object_id)
    sent = False

    if request.method == "POST":
        form = EmailPost(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            get_post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = "{} ({}) recommends you reding {}".format(cd['name'],cd['email'],post.title)
            message = "Read {} at {} \n\n{}\'s comments: {}".format(post.title,get_post_url,cd['name'],cd['comments'])

            send_mail(subject,message,"saikumarveeranki1@gmail.com",[cd['to']])
            sent = True

    else:
        form = EmailPost()

    return render(request,"blog/share.html",{"form":form,"post":post,"sent":sent})

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
  </head>
  <body>

    <header>
      <div class="head-body">

        <div class="site-urls">
          <ul>
            <li><a href="{% url 'blog:post_list' %}">Home</a></li>
          </ul>
        </div>

        <div class="authentication">

        </div>
        <div class="sub-site-urls">
          <a href="{% url 'blog:new_post' %}">+New Post</a>
        </div>

      </div>

    </header>
    <p>This blog contains {% total_posts %} posts so far.</p>
    <a href="{% url 'blog:post_feed' %}">RSS feed</a>

    <div class="lates-posts">
      <h3>latest posts</h3>
      {% show_latest_posts %}
    </div>

    <div class="most-commentd-posts">
      <h6>Most commented posts :</h6>
      {% get_most_commentd_posts as most_commentd %}
      <ul>
        {% for post in most_commentd %}
          <li>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
          </li>
        {% endfor %}
      </ul>
    </div>

    {% block content %}

    {% endblock content %}

  </body>
</html>

mysite/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}


{% block title %}{{post.title}} {% endblock title %}


{% block content %}
<div class="post-detail">
  <h3>{{post.title}} by {{post.author}} on {{post.publish}}</h3>
  <p>{{post.body|markdown}}</p>
  <a href="{% url 'blog:post_share' post.pk %}">Share</a>
  <br>
  <p>Comments:</p>
  {% with comments.count as total_comments %}
    <h3>{{total_comments}} comment {{total_comments|pluralize}}</h3>
  {% endwith %}

  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{forloop.counter}} by {{comment.name}} {{comment.created}}
      </p>
      {{comment.body}}
    </div>
    {% empty %}
      <p>There are no comments yet.</p>
  {% endfor %}

  {% if new_comment %}
    <p>Your Comment has been added.</p>


  {% else %}
  <h3>Add new comment</h3>
    <form class="" action="." method="post">
      {% csrf_token %}
      {{comment_form.as_p}}
      <button type="submit" name="button">Add comment</button>
    </form>

  {% endif %}



</div>

{% endblock content %}

mysite/blog/templates/blog/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    </li>

  {% endfor %}
</ul>

mysite/blog/templates/blog/list.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}Mushrooms {% endblock title %}


{% block content %}

<div class="Mushrooms-home">
  <h3>Mushrooms</h3>
    <!-- Remember must use page_obj while using pagination --!>
  {% for mushroom in page_obj %}
    <h4><a href="{% url 'blog:post_detail' mushroom.pk %}">{{mushroom.title}}</a></h4>
    <p>Tags: {{mushroom.tags.all|join:", "}}</p>
    <p>Published by {{mushroom.author}} on {{mushroom.publish}}</p>
    <p>{{ mushroom.body|markdown|truncatewords_html:30 }}</p>
  {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>



{% endblock content %}

mysite/blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}

{% block title %} Add new post {% endblock title %}

{% block content %}

<div class="new-post">
  <h1>Add New Post</h1>
  <form class="" action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" name="button">Create Post</button>
  </form>
</div>


{% endblock content %}

mysite/blog/templates/blog/share.html
{% extends 'blog/base.html' %}

{% block title %} {% endblock title %}

{% block content %}

<div class="post-share">
  {% if sent %}
    <div class="shared-post">
      <h3>Post sent success.</h3>
      <p>{{post.title}} was sent to {{form.cleaned_data.to}}.</p>
    </div>

  {% else %}
    <div class="share-now">
      <h3>Share {{post.title}}</h3>
      <form class="" action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" name="button">Share</button>
      </form>
    </div>

  {% endif %}
</div>


{% endblock content %}